// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc0.MyRobot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static AnalogInput driveInput;
    public static SpeedController driveLeft;
    public static SpeedController driveRight;
    public static DifferentialDrive drivemotors;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveInput = new AnalogInput(0);
        LiveWindow.addSensor("Drive", "Input", driveInput);
        
        driveLeft = new Spark(0);
        LiveWindow.addActuator("Drive", "Left", (Spark) driveLeft);
        driveLeft.setInverted(false);
        driveRight = new Spark(1);
        LiveWindow.addActuator("Drive", "Right", (Spark) driveRight);
        driveRight.setInverted(false);
        drivemotors = new DifferentialDrive(driveLeft, driveRight);
        LiveWindow.addActuator("Drive", "motors", drivemotors);
        drivemotors.setSafetyEnabled(true);
        drivemotors.setExpiration(0.1);
        drivemotors.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
